build:
	gcc cut_ribbon.c -o ribbon
	gcc subset_max_sum.c -o ssm
	gcc knapsack.c -o knapsack
	gcc longest_common_subsequence.c -o lcs
run:
	./ribbon
	./ssm
	./knapsack
	./lcs

clean:
	rm -f ribbon
	rm -f ssm
	rm -f knapsack
	rm -f lcs

