CC = g++

build:
	$(CC) teme.cpp -o teme
	$(CC) magic.cpp -o magic
	$(CC) ratisoare.cpp -o ratisoare
	$(CC) joc.cpp -o joc

run-p1:
	./teme
run-p2:
	./magic
run-p3:
	./ratisoare
run-p4:
	./joc

clean:
	rm -f *.o 
	rm teme 
	rm magic 
	rm joc 
	rm ratisoare

